baseurl = "https://helm.sh/"
languageCode = "en-us"
title = "Helm"
theme = "helm"

contentDir = "content"
publishdir = "app"

canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

[params]
  title = "Helm"
  author = "Ronan Flynn-Curran"
  description = "Helm - The Kubernetes Package Manager."

[Permalinks]
  code = "/:filename/"
